### ISSUE TITLE
Allow only whitelisted contracts to interact with SharesTimeLock.sol

### ISSUE THREAD

**Issue by Alexintosh** [MickdeGraaf/dividends#23]
The account which locks the tokens cannot be a smart contract in order to avoid making it tradable, unless it is one of the whitelisted smart contracts (such as widely used multi-sig wallets or yearn).

**Comment by Alexintosh** [comment]
```
function isContract(address _addr) private returns (bool isContract){
  uint32 size;
  assembly {
    size := extcodesize(_addr)
  }
  return (size > 0);
}
```

**Comment by MickdeGraaf** [comment]
#24

**Comment by MickdeGraaf** [comment]
Fixed. Now only whitelisted addresses which are a smart contract can deposit and only whitelisted addresses can deposit into another address.
