### ISSUE TITLE
Full Integration test

### ISSUE THREAD

**Issue by Alexintosh** [MickdeGraaf/dividends#5]
- Deploy the Timelock
- Deploy the ERC20 Non-Transferable Token
- Let the time pass
- Set Merkle Proof
- Verify the outcomes

Cases to cover:
- [x] Multiple accounts at the same time
- [x] One account at the same time
- [x] User who did not partecipate is not able to claim
- [x] User who was ejected cannot claim rewards
- [x] User who did partecipate is able to claim
- [x] User that have have his lock expired can be ejected

**Comment by Alexintosh** [comment]
@antodp updates?

**Comment by MickdeGraaf** [comment]
closed by #22
